### ISSUE TITLE
Transparent menus looks weird

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/blog#140]
<img width="686" alt="screen shot 2017-05-30 at 11 45 02 pm" src="https://cloud.githubusercontent.com/assets/1256298/26604153/16eb9e44-4592-11e7-948d-fc9eb59acba0.png">

**Comment by sergeyklay** [comment]
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4

**Comment by niden** [comment]
This has been resolved
