### ISSUE TITLE
Change color to more neutral and "standard" 

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/blog#193]
Use color from the color range as we use everywhere

![image](https://user-images.githubusercontent.com/1256298/50730290-733ed980-1152-11e9-83bf-af11b5a8aa1a.png)

**Comment by Arhell** [comment]
Hi @sergeyklay 
this color is used on the main site
I suggest using color with https://docs.phalconphp.com/ru/3.4 ?
http://joxi.ru/MAjdnlbt4M0y4m

**Comment by sergeyklay** [comment]
I would suggest  `#3E5664` as a main color and  `#122633` for hover :smile:

**Comment by Arhell** [comment]
Maybe use`#82ac95`, so that the blog has the support of one of the primary colors? Just more neutral.
Taken from the wing of the logo)

**Comment by sergeyklay** [comment]
Looks good to me

**Comment by niden** [comment]
Resolved
