### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by Arhell** [phalcon/blog#200]
Hello.
links do not work in the community menu:
1) API
2) Resources

**Comment by sergeyklay** [comment]
We will need to remove broken links from our blog posts. Another workaround is to use https://web.archive.org. Probable we can automate check URLs for the blog with some URL checker on the deploy stage.

/cc @niden

**Comment by niden** [comment]
All the links in the blog (blog posts) have been corrected. There are no dead links in the content.

The API link has been fixed.
The Resources one - I need to set that site up again

**Comment by Arhell** [comment]
Nice
thank @niden
