### ISSUE TITLE
No pagination

### ISSUE THREAD

**Issue by StudioMaX** [phalcon/blog#317]
Could you add pagination somewhere to make navigation on blog easier?

**Comment by ruudboon** [comment]
Good idea, we need to check what's possible with the Netlify CMS that is running the blog.

**Comment by ruudboon** [comment]
I think this can work. https://jekyllrb.com/docs/pagination/ 
See pull

**Comment by ruudboon** [comment]
@StudioMaX It's online! @Arhell can you check if the styling is good enough?

**Comment by Arhell** [comment]
Yes

**Comment by Arhell** [comment]
I add some styles
https://github.com/phalcon/assets/commit/221e62e1f443f32d93f20b3bfacd3f4728ba4ae7

**Comment by ruudboon** [comment]
thnx @Arhell
