### ISSUE TITLE
Social share image

### ISSUE THREAD

**Issue by ruudboon** [phalcon/blog#340]
Currently sharing our blog link wil result in something like this.
![83C53071-5484-482C-B70D-548BE01FC95D](https://user-images.githubusercontent.com/7444246/65444741-f9aa6100-de30-11e9-85eb-1b128bc20fe9.jpeg)

I would like to add the meta tags and image to our repo to show a phalcon related image.

**Comment by niden** [comment]
@Arhell Can you have a look please? Maybe we can use the images you have created (will create) for GitHub?

**Comment by Arhell** [comment]
Hi, what kind of pictures do we need?

**Comment by niden** [comment]
@Arhell The same images we created for the docs repository. What we discussed in Discord

**Comment by Arhell** [comment]
@ruudboon 
Hi finally earned
